---
- name: Copy MongoDB dump to remote server
  ansible.builtin.copy:
    src: ./.tmp/{{ application.name }}_{{ item.key }}.tar.gz
    dest: /tmp/mongodump/
    mode: '0644'
  with_dict: "{{ application.mongodb_collections_migration }}"
- name: Restore MongoDB database from dump
  ansible.builtin.shell: |
    mongorestore \
      --gzip \
      --archive=/tmp/mongodump/{{ application.name }}_{{ item.key }}.tar.gz
  register: restore_result
  changed_when: restore_result.rc == 0
  with_dict: "{{ application.mongodb_collections_migration }}"
- name: Remove MongoDB dumps and archive from remote server
  ansible.builtin.file:
    path: /tmp/mongodump/{{ application.name }}_{{ item.key }}.tar.gz
    state: absent
  with_dict: "{{ application.mongodb_collections_migration }}"
