---
  - name: install dependencies
    apt:
      name: libkrb5-dev
      state: present
    become: true
    tags: mes_aides

  - name: Install Git
    apt:
      name: git
      state: present
    tags: mes_aides

  - name: Update Mes Aides codebase
    git:
      repo: https://github.com/sgmap/mes-aides-ui.git
      dest: "{{ mes_aides.path }}"
      version: "{{ mes_aides.version }}"
      depth: 1
    tags: mes_aides

  - name: Install dependencies
    npm:
      path: "{{ mes_aides.path }}"
    tags: mes_aides


  - include: nginx.yml
