name: "Continuous Integration"
on:
  workflow_dispatch:
  pull_request:

jobs:
  install_python_requirements:
    name: Install Python requirements
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.4'
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Cache Python dependencies
        uses: actions/cache@v3
        id: python-dependencies
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-python-dependencies-${{ hashFiles('**/requirements.txt') }}
      - name: Install dependencies
        run: pip install -r requirements.txt
  lint_ansible_files:
    name: Lint ansible files
    runs-on: ubuntu-24.04
    needs: [install_python_requirements]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
      - name: Cache Python dependencies
        uses: actions/cache@v3
        id: python-dependencies
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-python-dependencies-${{ hashFiles('**/requirements.txt') }}
      - name: Check installed package
        run: pip freeze
      - name: Run ansible lint
        run: ansible-lint --offline
